version: "3.9"
services:
  server:
    image: "p4gefau1t/trojan-go"
    ports:
      - "443:443"
    volumes:
      - "./config/server.json:/etc/trojan-go/config.json"
      - "./cert:/root/cert"
    restart:
      on-failure
    extra_hosts:
      - "host.docker.internal:host-gateway"
  client:
    image: "p4gefau1t/trojan-go"
    ports:
      - "1080:1080"
    volumes:
      - "./config/client.json:/etc/trojan-go/config.json"
    restart:
      on-failure